### ISSUE TITLE
Chapter 2 Getting Started with Basic Plots - fix_yahoo_finance -import error

### ISSUE THREAD

**Issue by JosephKarpinski** [PacktPublishing/Matplotlib-3.0-Cookbook#2]
Chapter 2 Getting Started with Basic Plots - fix_yahoo_finance -import error

See attached below
<img width="1255" alt="Source" src="https://user-images.githubusercontent.com/37123616/123644112-11c3c700-d7f3-11eb-9030-e81b0ce2a5a6.png">
<img width="1204" alt="Error" src="https://user-images.githubusercontent.com/37123616/123644155-1be5c580-d7f3-11eb-9621-29d8d404ecec.png">
<img width="1195" alt="Fix" src="https://user-images.githubusercontent.com/37123616/123644175-20aa7980-d7f3-11eb-93aa-606294d29270.png">

**Comment by psvrao** [comment]
looks like yahoo came out with new package and you seem to have already figured out new package name as I can see successful run image above. Pls let me know, if I did not get the issue right.
